import { StyleSheet } from 'react-native';

export const baseCompoundStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#121212',
  },
  scrollContent: {
    padding: 16,
    paddingBottom: 32,
  },
  hero: {
    marginBottom: 16,
  },
  heroTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: 8,
  },
  heroSub: {
    fontSize: 13,
    color: '#9E9E9E',
    lineHeight: 20,
  },
  tabScroll: {
    marginTop: 8,
    marginBottom: 16,
  },
  tabRow: {
    flexDirection: 'row',
    gap: 8,
    paddingVertical: 4,
  },
  tabChip: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: 'rgba(51, 51, 51, 0.8)',
    borderWidth: 1,
    borderColor: 'rgba(66, 165, 245, 0.15)',
  },
  tabChipActive: {
    backgroundColor: 'rgba(66, 165, 245, 0.25)',
    borderColor: 'rgba(66, 165, 245, 0.55)',
  },
  tabChipText: {
    color: '#B0BEC5',
    fontSize: 13,
    fontWeight: '600',
  },
  tabChipTextActive: {
    color: '#FFFFFF',
  },
  card: {
    backgroundColor: 'rgba(45, 45, 45, 0.8)',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'rgba(66, 165, 245, 0.1)',
    padding: 16,
    marginBottom: 16,
  },
  cardTitle: {
    fontSize: 17,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: 12,
  },
  label: {
    fontSize: 14,
    color: '#B0BEC5',
    marginBottom: 8,
  },
  input: {
    backgroundColor: 'rgba(51, 51, 51, 0.6)',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(66, 165, 245, 0.2)',
    padding: 14,
    color: '#FFFFFF',
    fontSize: 17,
    marginBottom: 14,
  },
  inputDerived: {
    borderColor: 'rgba(144, 202, 249, 0.45)',
    color: '#B3E5FC',
  },
  percentRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 14,
  },
  percentInput: {
    flex: 1,
    minWidth: 0,
    marginBottom: 0,
  },
  signToggleBtn: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(42, 53, 68, 0.95)',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(66, 165, 245, 0.35)',
  },
  signToggleText: {
    color: '#90CAF9',
    fontSize: 18,
    fontWeight: '700',
  },
  helperText: {
    fontSize: 12,
    color: '#757575',
    marginTop: -8,
    marginBottom: 12,
    marginLeft: 2,
  },
  krwEquivalentBlock: {
    marginTop: 10,
    marginBottom: 4,
    padding: 10,
    borderRadius: 8,
    backgroundColor: 'rgba(66, 165, 245, 0.06)',
    borderWidth: 1,
    borderColor: 'rgba(66, 165, 245, 0.15)',
  },
  krwEquivalentTitle: {
    fontSize: 12,
    color: '#90CAF9',
    marginBottom: 6,
    fontWeight: '600',
  },
  krwEquivalentLine: {
    fontSize: 12,
    color: '#B0BEC5',
    lineHeight: 20,
  },
  chipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 12,
  },
  quickChip: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    backgroundColor: 'rgba(66, 165, 245, 0.12)',
    borderWidth: 1,
    borderColor: 'rgba(66, 165, 245, 0.25)',
  },
  quickChipText: {
    color: '#90CAF9',
    fontSize: 12,
    fontWeight: '600',
  },
  stepTable: {
    marginTop: 0,
    marginBottom: 8,
  },
  stepTableSectionTitle: {
    fontSize: 13,
    fontWeight: '600',
    color: '#90CAF9',
    marginTop: 12,
    marginBottom: 6,
  },
  stepHeader: {
    flexDirection: 'row',
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.08)',
  },
  stepRow: {
    flexDirection: 'row',
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.04)',
  },
  stepCell: {
    flex: 1,
    fontSize: 12,
    color: '#CFD8DC',
  },
  stepCellHead: {
    flex: 1,
    fontSize: 11,
    color: '#78909C',
    fontWeight: '600',
  },
  insightBox: {
    backgroundColor: 'rgba(66, 165, 245, 0.08)',
    borderRadius: 12,
    padding: 12,
    marginTop: 8,
    marginBottom: 4,
    borderWidth: 1,
    borderColor: 'rgba(66, 165, 245, 0.2)',
  },
  insightText: {
    fontSize: 13,
    color: '#B3E5FC',
    lineHeight: 20,
  },
  conceptTitle: {
    fontSize: 13,
    color: '#E1F5FE',
    fontWeight: '700',
    marginBottom: 6,
  },
  usageHintText: {
    fontSize: 12,
    color: '#757575',
    lineHeight: 18,
    marginBottom: 14,
  },
  resetTargetBtn: {
    alignSelf: 'flex-start',
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderRadius: 12,
    backgroundColor: 'rgba(66, 165, 245, 0.12)',
    borderWidth: 1,
    borderColor: 'rgba(66, 165, 245, 0.35)',
    marginTop: -6,
    marginBottom: 4,
  },
  resetTargetBtnDisabled: {
    opacity: 0.4,
  },
  resetTargetBtnText: {
    color: '#90CAF9',
    fontSize: 13,
    fontWeight: '600',
  },
  timelineText: {
    fontSize: 15,
    color: '#FFFFFF',
    fontWeight: '600',
    textAlign: 'center',
    marginVertical: 8,
  },
  resultGrid: {
    flexDirection: 'column',
    gap: 10,
    marginTop: 8,
  },
  exchangeRateRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 8,
    marginBottom: 16,
    gap: 8,
  },
  currencySwitchContainer: {
    marginBottom: 16,
  },
  exchangeRateText: {
    fontSize: 12,
    color: '#42A5F5',
  },
  modeRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 14,
  },
  modeChip: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 12,
    backgroundColor: 'rgba(51, 51, 51, 0.8)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
  },
  modeChipActive: {
    borderColor: 'rgba(66, 165, 245, 0.5)',
    backgroundColor: 'rgba(66, 165, 245, 0.15)',
  },
  modeChipText: {
    color: '#B0BEC5',
    fontSize: 12,
  },
  modeChipTextActive: {
    color: '#FFFFFF',
    fontWeight: '600',
  },
  pathStepList: {
    gap: 8,
    marginBottom: 12,
  },
  pathStepRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  pathStepIndex: {
    width: 28,
    fontSize: 13,
    color: '#78909C',
    fontWeight: '600',
    textAlign: 'center',
  },
  pathStepInput: {
    flex: 1,
    minWidth: 0,
    marginBottom: 0,
  },
  pathStepSuffix: {
    fontSize: 14,
    color: '#B0BEC5',
    width: 16,
  },
  pathRemoveBtn: {
    width: 36,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 10,
    backgroundColor: 'rgba(239, 83, 80, 0.12)',
    borderWidth: 1,
    borderColor: 'rgba(239, 83, 80, 0.25)',
  },
  pathRemoveBtnText: {
    color: '#EF5350',
    fontSize: 16,
    fontWeight: '600',
  },
  pathAddBtn: {
    alignSelf: 'flex-start',
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderRadius: 12,
    backgroundColor: 'rgba(66, 165, 245, 0.12)',
    borderWidth: 1,
    borderColor: 'rgba(66, 165, 245, 0.35)',
    marginBottom: 14,
  },
  pathAddBtnDisabled: {
    opacity: 0.4,
  },
  pathAddBtnText: {
    color: '#90CAF9',
    fontSize: 13,
    fontWeight: '600',
  },
  pathTimeline: {
    marginBottom: 12,
    paddingVertical: 4,
  },
  pathTimelineNodeRow: {
    flexDirection: 'row',
    minHeight: 72,
  },
  pathTimelineConnectorRow: {
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: 36,
  },
  pathTimelineRailCol: {
    width: 28,
    alignItems: 'center',
    alignSelf: 'stretch',
  },
  pathTimelineDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    borderWidth: 2,
    backgroundColor: '#121212',
  },
  pathTimelineDotStart: {
    borderColor: '#42A5F5',
    backgroundColor: 'rgba(66, 165, 245, 0.35)',
  },
  pathTimelineDotStep: {
    borderColor: '#78909C',
  },
  pathTimelineDotRecovery: {
    borderColor: '#FFB74D',
  },
  pathTimelineDotFinal: {
    borderColor: '#FFB74D',
    backgroundColor: 'rgba(255, 183, 77, 0.25)',
  },
  pathTimelineLine: {
    width: 2,
    flex: 1,
    minHeight: 20,
    backgroundColor: 'rgba(255,255,255,0.12)',
  },
  pathTimelineLineFlex: {
    width: 2,
    flex: 1,
    minHeight: 24,
    backgroundColor: 'rgba(255,255,255,0.12)',
  },
  pathTimelinePctChip: {
    flex: 1,
    marginLeft: 8,
    marginVertical: 2,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
    backgroundColor: 'rgba(51, 51, 51, 0.9)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    alignSelf: 'flex-start',
  },
  pathTimelinePctChipRecovery: {
    borderColor: 'rgba(255, 183, 77, 0.35)',
    backgroundColor: 'rgba(255, 183, 77, 0.08)',
  },
  pathTimelinePctChipText: {
    fontSize: 12,
    fontWeight: '700',
  },
  pathTimelineCard: {
    flex: 1,
    marginLeft: 8,
    marginBottom: 4,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 12,
    backgroundColor: 'rgba(51, 51, 51, 0.55)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
  },
  pathTimelineCardStart: {
    borderColor: 'rgba(66, 165, 245, 0.35)',
    backgroundColor: 'rgba(66, 165, 245, 0.08)',
  },
  pathTimelineCardFinal: {
    borderColor: 'rgba(255, 183, 77, 0.4)',
    backgroundColor: 'rgba(255, 183, 77, 0.08)',
  },
  pathTimelineCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 4,
    gap: 8,
  },
  pathTimelineLabel: {
    fontSize: 12,
    color: '#90CAF9',
    fontWeight: '700',
  },
  pathTimelineCumulative: {
    fontSize: 11,
    fontWeight: '600',
  },
  pathTimelinePrice: {
    fontSize: 17,
    color: '#FFFFFF',
    fontWeight: '700',
  },
  disclaimer: {
    fontSize: 11,
    color: '#616161',
    lineHeight: 16,
    marginTop: 8,
    marginBottom: 16,
  },
});
